export enum ReturnReason {
  DEFECTIVE = 'DEFECTIVE',
  WRONG_ITEM = 'WRONG_ITEM',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  DAMAGED_IN_TRANSIT = 'DAMAGED_IN_TRANSIT',
  SIZE_FIT = 'SIZE_FIT',
  CHANGED_MIND = 'CHANGED_MIND',
  OTHER = 'OTHER',
}
