import { ApiProperty } from '@nestjs/swagger';
import { IsInt, IsObject, IsString, Max, MaxLength, Min } from 'class-validator';

export class SavePdfDraftDto {
  @ApiProperty({
    maxLength: 191,
    description: 'Stable document key generated by frontend (hash + metadata).',
  })
  @IsString()
  @MaxLength(191)
  documentKey: string;

  @ApiProperty({ maxLength: 255 })
  @IsString()
  @MaxLength(255)
  fileName: string;

  @ApiProperty({ minimum: 1, maximum: 5000 })
  @IsInt()
  @Min(1)
  @Max(5000)
  totalPages: number;

  @ApiProperty({
    description: 'Serialized PDF annotations and editor state.',
    type: 'object',
    additionalProperties: true,
  })
  @IsObject()
  draft: Record<string, unknown>;
}
